


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ConvexClientProvider } from "./ConvexClientProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
//         <ConvexClientProvider>{children}</ConvexClientProvider>
//       </body>
//     </html>
//   );
// }

















// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ClerkProvider, SignedIn, SignedOut, RedirectToSignIn } from "@clerk/nextjs";
// import { ConvexClientProvider } from "./ConvexClientProvider";
// import Navbar from "@/components/Navbar";




// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <ClerkProvider>
//           <SignedIn>
//             <Navbar />
//             <ConvexClientProvider>{children}</ConvexClientProvider>
//           </SignedIn>
          
//         </ClerkProvider>
//       </body>
//     </html>
//   );
// }















import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Navbar from "@/components/Navbar";



// Load IBM Plex Mono fonts
const IBMPlexMonoBold = localFont({
  src: "./fonts/IBMPlexMono-Bold.ttf",
  variable: "--font-imb-bold",
  display: "swap",
});
const IBMPlexMonoMedium = localFont({
  src: "./fonts/IBMPlexMono-Medium.ttf",
  variable: "--font-imb-medium",
  display: "swap",
});
const IBMPlexMonoRegular = localFont({
  src: "./fonts/IBMPlexMono-Regular.ttf",
  variable: "--font-imb-regular",
  display: "swap",
});

// Combine all font variables
const combinedFonts = `${IBMPlexMonoBold.variable} ${IBMPlexMonoMedium.variable} ${IBMPlexMonoRegular.variable}`;


export const metadata: Metadata = {
  title: "Cars",
  description: "Car renting web app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={combinedFonts}>
      <body className="antialiased">
        <ClerkProvider>
          {/* Navbar always visible */}
          <Navbar />
          
          {/* App content */}
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
